### ISSUE TITLE
Adding to community list

### ISSUE THREAD

**Issue by maniackcrudelis** [jodeko/glowing_bear_ynh#1]
Hello jodeko,

Thanks for your package, it's always great to see new packages added to YunoHost.

But, we added your package in "inprogress" category, because, in state, your package does not work out-of-the-box.
The package works, an the setup causes no errors, but at the end of the setup, Glowing Bear needs a running instance of Weechat.

For considering Glowing Bear as a working Apps, it's necessary that the package installs Weechat with Glowing Bear already setup for use it.

**Comment by jodeko** [comment]
Dear maniacrudelis,

first of all, thank you very much for your feedback as well as your work for yunohost!

I'm unsure if I can follow your decision to mark this app as "in progress" to be honest:

Glowing Bear is a Weechat relay client app that runs in the browser.  This is entirely independent from where the Weechat instance (relay/server) is running. The user has to provide the correct access/connection credentials in order to make proper use of Glowing Bear. So this ynh app here acts exactly the same way as if you would manually download and "install" Glowing Bear on your server. I think this should be precisely the expectation users can have when they install this ynh app. So in my opinion this app is "working" correctly.  

Creating a ynh app that installs, configures and runs Weechat to be accessible from a remote client is a totally different story and potentially much more complex depending on the requirements. If you say there is a need for this I would be happy to look into this.

Regarding this Glowing Bear app here, however, I would be very happy if you would move it to the "working" list. 

Thank you kindly

jodeko

**Comment by maniackcrudelis** [comment]
I'm understand what you said.
And, globally, I'm ok with you, your app Glowing Bear is functionals and ready to use.
But, for a rookie user, after the app install, the app need a Weechat server to work. And he doen't have it.

So, at least, add a explaination in the readme file to clarify that is only a client, without server side.
With this, we can consider the app is functionnal. (I'm agree, it's juste a sentence in a readme ;) )

And it's really better if you can add a Weechat server, either with a option in the manifest to install the server and preconfigure the client. Either by a separate package to install only the Weechat server (with a documentation to explain how to connect them, without CLI of course)

Like that, you bring a complete experience with Weechat for all users.

Are you agree with me ?

**Comment by jodeko** [comment]
Yes I totally agree with you. Are you satisfied with the updated README?

**Comment by maniackcrudelis** [comment]
Seems like good for me.

Can you just change "for your WeeChat instance." for "for the WeeChat instance." ?
Just to avoid confusion.

I'll change the status of your app right now ;)

**Comment by jodeko** [comment]
done and closing issue :-)
